# -*- mode: python ; coding: utf-8 -*-

a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[('library', 'library')],
    hiddenimports=[
        'PySide6.QtCore',
        'PySide6.QtGui',
        'PySide6.QtWidgets',
        'matplotlib',
        'matplotlib.backends.backend_qtagg',
        'serial',
        'serial.tools.list_ports',
        'logging',
        'logging.handlers',
        'core.bootloader',
        'core.can_protocol',
        'core.dbc_manager',
        'core.dbc_parser',
        'core.fake_serial',
        'core.script_engine',
        'core.serial_manager',
        'core.update_checker',
        'models.config',
        'models.logger',
        'models.translations',
        'models.utils',
        'ui.can_analyzer',
        'ui.can_gateway_tab',
        'ui.can_graph_tab',
        'ui.can_monitor_tab',
        'ui.can_trigger_tab',
        'ui.com_settings_dialog',
        'ui.dark_theme',
        'ui.firmware_page',
        'ui.flexible_logic_tab',
        'ui.library_browser',
        'ui.script_editor',
        'ui.settings_window',
        'ui.signal_graph_tab',
        'ui.ui_utils',
        'pyqtgraph',
        'cantools',
        'cantools.database',
        'carbus_async',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    noarchive=False,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='CodeMaster',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='CodeMaster',
)

app = BUNDLE(
    coll,
    name='CodeMaster.app',
    icon='assets/icon.icns',
    bundle_identifier='com.codemaster.app',
)
